import type { Metadata } from 'next';
import { Header, Sidebar, Footer } from '@/components';
import { Noto_Sans } from 'next/font/google';
import './globals.css';

const notoSans = Noto_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Rating App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${notoSans.className}`}>
        <div className="wrapper">
          <Header />
          <Sidebar />
          <div className="body">
            <div>{children}</div>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
